/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.IngresosDAO;
import java.time.LocalDate;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelo.Ingresos;
import modelo.Usuario;

/**
 *
 * @author NOTE
 */
public class VentModificarIngresos extends javax.swing.JFrame {
    
    private Usuario usu;

    /**
     * Creates new form VentModificarIngresos
     */
    public VentModificarIngresos(Usuario usu) {
        initComponents();
        this.usu = usu;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNombreIngreso = new javax.swing.JLabel();
        lblFechaIngreso = new javax.swing.JLabel();
        lblMontoIngreso = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        lblUnico = new javax.swing.JLabel();
        txtNombreIngreso = new javax.swing.JTextField();
        txtMontoIngreso = new javax.swing.JTextField();
        chboxFijo = new java.awt.Checkbox();
        btnIngresarIngreso = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtDiaIngreso = new javax.swing.JTextField();
        txtMesIngreso = new javax.swing.JTextField();
        txtAnioIngreso = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblGestorFinanciero1 = new javax.swing.JLabel();
        lblGestorFinanciero = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblRegistroIngreso = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombreIngreso.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lblNombreIngreso.setText("Nombre Ingreso");
        jPanel1.add(lblNombreIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        lblFechaIngreso.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lblFechaIngreso.setText("Fecha Ingreso");
        jPanel1.add(lblFechaIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, -1));

        lblMontoIngreso.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lblMontoIngreso.setText("Monto Ingreso");
        jPanel1.add(lblMontoIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, -1));

        btnVolver.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 440, -1, -1));

        lblUnico.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lblUnico.setText("Fijo");
        jPanel1.add(lblUnico, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, -1, -1));

        txtNombreIngreso.setBorder(null);
        txtNombreIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreIngresoActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombreIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 314, -1));

        txtMontoIngreso.setBorder(null);
        jPanel1.add(txtMontoIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 314, -1));
        jPanel1.add(chboxFijo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, -1, -1));

        btnIngresarIngreso.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        btnIngresarIngreso.setText("Ingresar");
        btnIngresarIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarIngresoActionPerformed(evt);
            }
        });
        jPanel1.add(btnIngresarIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, -1, -1));

        jLabel6.setText("/");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, -1, -1));

        txtDiaIngreso.setFont(new java.awt.Font("Roboto Light", 0, 16)); // NOI18N
        txtDiaIngreso.setForeground(new java.awt.Color(153, 153, 153));
        txtDiaIngreso.setText("dd");
        txtDiaIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiaIngresoActionPerformed(evt);
            }
        });
        jPanel1.add(txtDiaIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, -1, -1));

        txtMesIngreso.setFont(new java.awt.Font("Roboto Light", 0, 16)); // NOI18N
        txtMesIngreso.setForeground(new java.awt.Color(153, 153, 153));
        txtMesIngreso.setText("mm");
        txtMesIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMesIngresoActionPerformed(evt);
            }
        });
        jPanel1.add(txtMesIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, -1, -1));

        txtAnioIngreso.setFont(new java.awt.Font("Roboto Light", 0, 16)); // NOI18N
        txtAnioIngreso.setForeground(new java.awt.Color(153, 153, 153));
        txtAnioIngreso.setText("aa");
        jPanel1.add(txtAnioIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, -1, -1));

        jLabel5.setText("/");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/contabilidad.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        lblGestorFinanciero1.setBackground(new java.awt.Color(255, 255, 255));
        lblGestorFinanciero1.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        lblGestorFinanciero1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGestorFinanciero1.setText("MI GESTOR");
        jPanel1.add(lblGestorFinanciero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 12, 270, 50));

        lblGestorFinanciero.setBackground(new java.awt.Color(255, 255, 255));
        lblGestorFinanciero.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        lblGestorFinanciero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGestorFinanciero.setText("FINACIERO");
        jPanel1.add(lblGestorFinanciero, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 32, 270, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sistema-financiero.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(617, 0, 210, -1));

        lblRegistroIngreso.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblRegistroIngreso.setText("REGISTRAR INGRESO");
        jPanel1.add(lblRegistroIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 300, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 300, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarIngresoActionPerformed
        int monto = Integer.parseInt(txtMontoIngreso.getText());
        
        int dia = Integer.parseInt(txtDiaIngreso.getText());
        int mes = Integer.parseInt(txtMesIngreso.getText());
        int anio = Integer.parseInt("20"+txtAnioIngreso.getText());
        
        LocalDate fecha = LocalDate.of(anio, mes, dia);
        
        String nombre = txtNombreIngreso.getText();
        boolean fijo = chboxFijo.getState();
        
        Ingresos ing = new Ingresos(monto, fecha, nombre, fijo);
        
        IngresosDAO ingDAO = new IngresosDAO();
        
        if (ingDAO.registrarIngreso(ing, usu)) {
            JOptionPane.showMessageDialog(this, "Ingreso registrado exitosamente.");
            txtDiaIngreso.setText(null);
            txtMesIngreso.setText(null);
            txtAnioIngreso.setText(null);
            
            txtNombreIngreso.setText(null);
            txtMontoIngreso.setText(null);
        } else {
            JOptionPane.showMessageDialog(this, "No se ha podido registrar el ingreso.");
        }
    }//GEN-LAST:event_btnIngresarIngresoActionPerformed

    private void txtDiaIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiaIngresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiaIngresoActionPerformed

    private void txtMesIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMesIngresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMesIngresoActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
            VentPrincipal ventIn = new VentPrincipal(this.usu);
            ventIn.setLocationRelativeTo(null);
            ventIn.setTitle("PRINCIPAL");
            ventIn.setResizable(false);
            ventIn.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            ventIn.setVisible(true); 
            dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void txtNombreIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreIngresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreIngresoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresarIngreso;
    private javax.swing.JButton btnVolver;
    private java.awt.Checkbox chboxFijo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblFechaIngreso;
    private javax.swing.JLabel lblGestorFinanciero;
    private javax.swing.JLabel lblGestorFinanciero1;
    private javax.swing.JLabel lblMontoIngreso;
    private javax.swing.JLabel lblNombreIngreso;
    private javax.swing.JLabel lblRegistroIngreso;
    private javax.swing.JLabel lblUnico;
    private javax.swing.JTextField txtAnioIngreso;
    private javax.swing.JTextField txtDiaIngreso;
    private javax.swing.JTextField txtMesIngreso;
    private javax.swing.JTextField txtMontoIngreso;
    private javax.swing.JTextField txtNombreIngreso;
    // End of variables declaration//GEN-END:variables
}
