package vista;

import controlador.TarjetaDAO;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelo.Usuario;
import modelo.TarjetaCredito;



public class VentModificarProducto extends javax.swing.JFrame {
    
    public Usuario usu;

    /**
     * Creates new form VentModificarProducto
     */
    public VentModificarProducto(Usuario usu) {
        this.usu = usu;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnIngresar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        txtNombreProducto = new javax.swing.JTextField();
        txtCupo = new javax.swing.JTextField();
        txtDiaFacturacion = new javax.swing.JTextField();
        lblGestorFinanciero1 = new javax.swing.JLabel();
        lblGestorFinanciero = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblRegistroProducto = new javax.swing.JLabel();
        lblNombreTarjeta = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblCupo = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblDiaFacturacion = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnIngresar.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        btnIngresar.setText("Ingresar Tarjeta");
        btnIngresar.setBorder(null);
        btnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 430, 140, 40));

        btnVolver.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.setBorder(null);
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 430, 80, 40));

        txtNombreProducto.setBorder(null);
        txtNombreProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreProductoActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 310, 40));

        txtCupo.setBorder(null);
        jPanel1.add(txtCupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 310, 40));

        txtDiaFacturacion.setBorder(null);
        jPanel1.add(txtDiaFacturacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 130, 40));

        lblGestorFinanciero1.setBackground(new java.awt.Color(255, 255, 255));
        lblGestorFinanciero1.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        lblGestorFinanciero1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGestorFinanciero1.setText("MI GESTOR");
        jPanel1.add(lblGestorFinanciero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 12, 270, 50));

        lblGestorFinanciero.setBackground(new java.awt.Color(255, 255, 255));
        lblGestorFinanciero.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        lblGestorFinanciero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGestorFinanciero.setText("FINACIERO");
        jPanel1.add(lblGestorFinanciero, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 32, 270, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/contabilidad.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sistema-financiero.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(617, 0, 210, -1));

        lblRegistroProducto.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblRegistroProducto.setText("REGISTRAR TARJETA");
        jPanel1.add(lblRegistroProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        lblNombreTarjeta.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lblNombreTarjeta.setText("Nombre Tarjeta");
        jPanel1.add(lblNombreTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 320, 20));

        lblCupo.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lblCupo.setText("Cupo");
        jPanel1.add(lblCupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 320, 20));

        lblDiaFacturacion.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lblDiaFacturacion.setText("Día de Facturación");
        jPanel1.add(lblDiaFacturacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, 20));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 130, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 801, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreProductoActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
            VentPrincipal ventIn = new VentPrincipal(this.usu);
            ventIn.setLocationRelativeTo(null);
            ventIn.setTitle("PRINCIPAL");
            ventIn.setResizable(false);
            ventIn.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            ventIn.setVisible(true); 
            dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        String nombre;
        int diaFacturacion, cupo;
        
        nombre = txtNombreProducto.getText();
        cupo = Integer.parseInt(txtCupo.getText());
        diaFacturacion = Integer.parseInt(txtDiaFacturacion.getText());
        
        TarjetaCredito tar = new TarjetaCredito(usu.getIdUsuario(), nombre, diaFacturacion, cupo);
        
        TarjetaDAO tarDAO = new TarjetaDAO();
        
        if (tarDAO.buscarTarjetaCredito(usu, tar) == null) {
            tarDAO.ingresarTarjetaCredito(usu, tar);
            JOptionPane.showMessageDialog(this, "Tarjeta agredada con exito");
            txtNombreProducto.setText(null);
            txtCupo.setText(null);
            txtDiaFacturacion.setText(null);
        } else {
            JOptionPane.showMessageDialog(this, "Tarjeta ya existe con este usuario, elije otro nombre para la tarjeta.");
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblCupo;
    private javax.swing.JLabel lblDiaFacturacion;
    private javax.swing.JLabel lblGestorFinanciero;
    private javax.swing.JLabel lblGestorFinanciero1;
    private javax.swing.JLabel lblNombreTarjeta;
    private javax.swing.JLabel lblRegistroProducto;
    private javax.swing.JTextField txtCupo;
    private javax.swing.JTextField txtDiaFacturacion;
    private javax.swing.JTextField txtNombreProducto;
    // End of variables declaration//GEN-END:variables
}
