package vista;

import controlador.Gasto_cuotasDAO;
import controlador.GastosDAO;
import controlador.TarjetaDAO;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelo.Usuario;
import modelo.Gasto;
import modelo.GastoCuotas;
import modelo.TarjetaCredito;

public class VentModificarGastos extends javax.swing.JFrame {
    
    private Usuario usu;

    /**
     * Creates new form VentModificarGastos
     */
    public VentModificarGastos(Usuario usu) {
        initComponents();
        this.usu = usu;
        lblFechaGasto.hide();
        lblMontoCuota.hide();
        lblMontoTotalGasto.hide();
        lblNombreGasto.hide();
        lblSeparador1.hide();
        lblSeparador2.hide();
        lblTarjetaAsociada.hide();
        //lblTitulo.hide();
        txtAnioGasto.hide();
        txtDiaGasto.hide();
        txtMesGasto.hide();
        txtMontoCuota.hide();
        txtMontoTotalGasto.hide();
        txtNombreGasto.hide();
        txtNumCuotas.hide();
        lblNumCuota.hide();
        jcTarjetas.hide();
        
        btnIngresar.hide();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtAnioGasto = new javax.swing.JTextField();
        lblTipoGasto = new javax.swing.JLabel();
        lblSeparador1 = new javax.swing.JLabel();
        jcTipoGasto = new javax.swing.JComboBox<>();
        lblSeparador2 = new javax.swing.JLabel();
        lblNombreGasto = new javax.swing.JLabel();
        lblMontoCuota = new javax.swing.JLabel();
        lblFechaGasto = new javax.swing.JLabel();
        lblNumCuota = new javax.swing.JLabel();
        lblMontoTotalGasto = new javax.swing.JLabel();
        lblTarjetaAsociada = new javax.swing.JLabel();
        txtMontoCuota = new javax.swing.JTextField();
        txtNombreGasto = new javax.swing.JTextField();
        txtNumCuotas = new javax.swing.JTextField();
        txtMontoTotalGasto = new javax.swing.JTextField();
        jcTarjetas = new javax.swing.JComboBox<>();
        txtDiaGasto = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JButton();
        txtMesGasto = new javax.swing.JTextField();
        btnVolver = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblGestorFinanciero1 = new javax.swing.JLabel();
        lblGestorFinanciero = new javax.swing.JLabel();
        lblDetalleGasto = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAnioGasto.setFont(new java.awt.Font("Roboto Light", 0, 16)); // NOI18N
        txtAnioGasto.setForeground(new java.awt.Color(153, 153, 153));
        txtAnioGasto.setText("aa");
        jPanel1.add(txtAnioGasto, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, -1, -1));

        lblTipoGasto.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lblTipoGasto.setText("Tipo de gasto");
        jPanel1.add(lblTipoGasto, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, -1, -1));

        lblSeparador1.setText("/");
        jPanel1.add(lblSeparador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, -1, -1));

        jcTipoGasto.setFont(new java.awt.Font("Roboto Light", 0, 17)); // NOI18N
        jcTipoGasto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione tipo de gasto...", "Fijo", "Unico", "Cuotas" }));
        jcTipoGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcTipoGastoActionPerformed(evt);
            }
        });
        jPanel1.add(jcTipoGasto, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, -1, -1));

        lblSeparador2.setText("/");
        jPanel1.add(lblSeparador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, -1, -1));

        lblNombreGasto.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lblNombreGasto.setText("Nombre");
        jPanel1.add(lblNombreGasto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        lblMontoCuota.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lblMontoCuota.setText("Monto Cuota");
        jPanel1.add(lblMontoCuota, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, -1, -1));

        lblFechaGasto.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lblFechaGasto.setText("Fecha");
        jPanel1.add(lblFechaGasto, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, -1, -1));

        lblNumCuota.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lblNumCuota.setText("Nro cuotas");
        jPanel1.add(lblNumCuota, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, -1, -1));

        lblMontoTotalGasto.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lblMontoTotalGasto.setText("Monto Total");
        jPanel1.add(lblMontoTotalGasto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        lblTarjetaAsociada.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        lblTarjetaAsociada.setText("Tarjeta");
        jPanel1.add(lblTarjetaAsociada, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        txtMontoCuota.setFont(new java.awt.Font("Roboto Light", 0, 16)); // NOI18N
        txtMontoCuota.setBorder(null);
        jPanel1.add(txtMontoCuota, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 143, -1));

        txtNombreGasto.setFont(new java.awt.Font("Roboto Light", 0, 16)); // NOI18N
        txtNombreGasto.setBorder(null);
        jPanel1.add(txtNombreGasto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 260, -1));

        txtNumCuotas.setFont(new java.awt.Font("Roboto Light", 0, 16)); // NOI18N
        txtNumCuotas.setBorder(null);
        jPanel1.add(txtNumCuotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, 45, -1));

        txtMontoTotalGasto.setFont(new java.awt.Font("Roboto Light", 0, 16)); // NOI18N
        txtMontoTotalGasto.setBorder(null);
        jPanel1.add(txtMontoTotalGasto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 260, -1));

        jcTarjetas.setFont(new java.awt.Font("Roboto Light", 0, 16)); // NOI18N
        jPanel1.add(jcTarjetas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 260, -1));

        txtDiaGasto.setFont(new java.awt.Font("Roboto Light", 0, 16)); // NOI18N
        txtDiaGasto.setForeground(new java.awt.Color(153, 153, 153));
        txtDiaGasto.setText("dd");
        txtDiaGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiaGastoActionPerformed(evt);
            }
        });
        jPanel1.add(txtDiaGasto, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, -1, -1));

        btnIngresar.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        btnIngresar.setText("Ingresar Gasto");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, -1, -1));

        txtMesGasto.setFont(new java.awt.Font("Roboto Light", 0, 16)); // NOI18N
        txtMesGasto.setForeground(new java.awt.Color(153, 153, 153));
        txtMesGasto.setText("mm");
        txtMesGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMesGastoActionPerformed(evt);
            }
        });
        jPanel1.add(txtMesGasto, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, -1, -1));

        btnVolver.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 410, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/contabilidad.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        lblGestorFinanciero1.setBackground(new java.awt.Color(255, 255, 255));
        lblGestorFinanciero1.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        lblGestorFinanciero1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGestorFinanciero1.setText("MI GESTOR");
        jPanel1.add(lblGestorFinanciero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 12, 270, 50));

        lblGestorFinanciero.setBackground(new java.awt.Color(255, 255, 255));
        lblGestorFinanciero.setFont(new java.awt.Font("Roboto Light", 1, 18)); // NOI18N
        lblGestorFinanciero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGestorFinanciero.setText("FINACIERO");
        jPanel1.add(lblGestorFinanciero, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 32, 270, 50));

        lblDetalleGasto.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblDetalleGasto.setText("DETALLE GASTO");
        jPanel1.add(lblDetalleGasto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Sistema-financiero.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 0, 110, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 270, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 270, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 140, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, -1, -1));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 80, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDiaGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiaGastoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiaGastoActionPerformed

    private void txtMesGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMesGastoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMesGastoActionPerformed

    private void jcTipoGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcTipoGastoActionPerformed
        
        if (jcTipoGasto.getSelectedItem().toString().equals("Fijo")) {
            agregarGastoFijo();
        } else if (jcTipoGasto.getSelectedItem().toString().equals("Unico")) {
            agregarGastoUnico();
        } else if (jcTipoGasto.getSelectedItem().toString().equals("Cuotas")) {
            agregarGastoCuotas();
        }
    }//GEN-LAST:event_jcTipoGastoActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        if (jcTipoGasto.getSelectedItem().toString().equals("Fijo")) {
            ingresarGastoSinCuotas();
        } else if (jcTipoGasto.getSelectedItem().toString().equals("Unico")) {
            ingresarGastoSinCuotas();
        } else if (jcTipoGasto.getSelectedItem().toString().equals("Cuotas")) {
            ingresarGastoCuotas();
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
            VentPrincipal ventIn = new VentPrincipal(this.usu);
            ventIn.setLocationRelativeTo(null);
            ventIn.setTitle("PRINCIPAL");
            ventIn.setResizable(false);
            ventIn.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            ventIn.setVisible(true); 
            dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void ingresarGastoSinCuotas(){
        GastosDAO gasDAO = new GastosDAO();
        String dia = txtDiaGasto.getText();
        String mes = txtMesGasto.getText();
        String anio = "20"+txtAnioGasto.getText();
        
 
        Date fecha = new Date(mes+"/"+dia+"/"+anio);
        
        boolean unico = false;
        if (jcTipoGasto.getSelectedItem().toString().equals("Fijo")) {
            unico = false;
        } else if (jcTipoGasto.getSelectedItem().toString().equals("Unico")) {
            unico = true;
        }
        
        Gasto gas = new Gasto(usu.getIdUsuario(), Integer.parseInt(txtMontoTotalGasto.getText()),
                fecha, txtNombreGasto.getText(),unico);
        
        if (gasDAO.ingresarGasto(gas, usu)) {
            JOptionPane.showMessageDialog(this, "Gasto ingresado correctamente.");
            txtDiaGasto.setText(null);
            txtMesGasto.setText(null);
            txtAnioGasto.setText(null);
            txtMontoTotalGasto.setText(null);
            txtNombreGasto.setText(null);
        } else {
            JOptionPane.showMessageDialog(this, "No se ha podido ingresar el gasto.");
        }
        
        
    }
    
    private void ingresarGastoCuotas(){
        Gasto_cuotasDAO gasDAO = new Gasto_cuotasDAO();
        TarjetaDAO tarDAO = new TarjetaDAO();
        int numCuotas = Integer.parseInt(txtNumCuotas.getText());
        int montoCuotas = Integer.parseInt(txtMontoCuota.getText());
        int montoTotal = Integer.parseInt(txtMontoTotalGasto.getText());
        
        int dia = Integer.parseInt(txtDiaGasto.getText());
        int mes = Integer.parseInt(txtMesGasto.getText());
        int anio = Integer.parseInt("20"+txtAnioGasto.getText());
        LocalDateTime fecha = LocalDateTime.of(anio,mes,dia,12,00);
        String nombre = txtNombreGasto.getText();
        
        GastoCuotas gas = new GastoCuotas(numCuotas, montoCuotas, fecha, montoTotal,  nombre);
        
        TarjetaCredito tarEncontrada = new TarjetaCredito(usu.getIdUsuario(), jcTarjetas.getSelectedItem().toString(), 0, 0);
        TarjetaCredito tar = tarDAO.buscarTarjetaCredito(usu, tarEncontrada);
        
        int idGasto = gasDAO.ingresarGasto(tar, gas);
        gas.setId_gasto(idGasto);
        gas.setId_tarjeta(tar.getId_tarjeta());
        
        gas.llenarDetalle(tar);
        
        if (gasDAO.ingresarDetalle(gas)) {
            JOptionPane.showMessageDialog(this, "Gasto ingresado correctamente.");
            txtDiaGasto.setText(null);
            txtMesGasto.setText(null);
            txtAnioGasto.setText(null);
            txtMontoTotalGasto.setText(null);
            txtNombreGasto.setText(null);
            
            txtMontoCuota.setText(null);
            txtNumCuotas.setText(null);
        } else {
            JOptionPane.showMessageDialog(this, "No se ha podido ingresar el gasto.");
        }
       
        
        
    }

    private void agregarGastoFijo() {
        lblNombreGasto.setVisible(rootPaneCheckingEnabled);
        lblMontoTotalGasto.setVisible(rootPaneCheckingEnabled);
        lblFechaGasto.setVisible(rootPaneCheckingEnabled);
        lblSeparador1.setVisible(rootPaneCheckingEnabled);
        lblSeparador2.setVisible(rootPaneCheckingEnabled);
        
        txtNombreGasto.setVisible(rootPaneCheckingEnabled);
        txtDiaGasto.setVisible(rootPaneCheckingEnabled);
        txtMesGasto.setVisible(rootPaneCheckingEnabled);
        txtAnioGasto.setVisible(rootPaneCheckingEnabled);
        txtMontoTotalGasto.setVisible(rootPaneCheckingEnabled);     
        
        lblMontoCuota.hide();
        lblNumCuota.hide();
        lblTarjetaAsociada.hide();
        
        txtMontoCuota.hide();
        txtNumCuotas.hide();
        jcTarjetas.hide();
        
        btnIngresar.setVisible(rootPaneCheckingEnabled);
       
    }
    
    private void agregarGastoUnico() {
        lblNombreGasto.setVisible(rootPaneCheckingEnabled);
        lblMontoTotalGasto.setVisible(rootPaneCheckingEnabled);
        lblFechaGasto.setVisible(rootPaneCheckingEnabled);
        lblSeparador1.setVisible(rootPaneCheckingEnabled);
        lblSeparador2.setVisible(rootPaneCheckingEnabled);
        
        txtNombreGasto.setVisible(rootPaneCheckingEnabled);
        txtDiaGasto.setVisible(rootPaneCheckingEnabled);
        txtMesGasto.setVisible(rootPaneCheckingEnabled);
        txtAnioGasto.setVisible(rootPaneCheckingEnabled);
        txtMontoTotalGasto.setVisible(rootPaneCheckingEnabled);    
        
        lblMontoCuota.hide();
        lblNumCuota.hide();
        lblTarjetaAsociada.hide();
        
        txtMontoCuota.hide();
        txtNumCuotas.hide();
        jcTarjetas.hide();
        
        btnIngresar.setVisible(rootPaneCheckingEnabled);
    }
    
    private void agregarGastoCuotas() {
        lblNombreGasto.setVisible(rootPaneCheckingEnabled);
        lblMontoTotalGasto.setVisible(rootPaneCheckingEnabled);
        lblFechaGasto.setVisible(rootPaneCheckingEnabled);
        lblSeparador1.setVisible(rootPaneCheckingEnabled);
        lblSeparador2.setVisible(rootPaneCheckingEnabled);
        
        txtNombreGasto.setVisible(rootPaneCheckingEnabled);
        txtDiaGasto.setVisible(rootPaneCheckingEnabled);
        txtMesGasto.setVisible(rootPaneCheckingEnabled);
        txtAnioGasto.setVisible(rootPaneCheckingEnabled);
        txtMontoTotalGasto.setVisible(rootPaneCheckingEnabled);   
        
        lblMontoCuota.setVisible(rootPaneCheckingEnabled);
        lblNumCuota.setVisible(rootPaneCheckingEnabled);
        lblTarjetaAsociada.setVisible(rootPaneCheckingEnabled);
        
        txtMontoCuota.setVisible(rootPaneCheckingEnabled);
        txtNumCuotas.setVisible(rootPaneCheckingEnabled);
        jcTarjetas.setVisible(rootPaneCheckingEnabled);
        
        btnIngresar.setVisible(rootPaneCheckingEnabled);
        
        jcTarjetas.addItem("Selecciona");
        TarjetaDAO buscador = new TarjetaDAO();
        ArrayList<TarjetaCredito> lista = new ArrayList<TarjetaCredito>(); 
        buscador.buscarTarjetasCredito(usu,lista);
        if (lista.size() == 0) {
            JOptionPane.showMessageDialog(this, "No existen tarjetas de creditos asociadas a tu usuario.");
        } else {
            lista.forEach((agregarTar) -> {
                jcTarjetas.addItem(agregarTar.getNombre_tarjeta());
            });
        }
        
        
    }
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JComboBox<String> jcTarjetas;
    private javax.swing.JComboBox<String> jcTipoGasto;
    private javax.swing.JLabel lblDetalleGasto;
    private javax.swing.JLabel lblFechaGasto;
    private javax.swing.JLabel lblGestorFinanciero;
    private javax.swing.JLabel lblGestorFinanciero1;
    private javax.swing.JLabel lblMontoCuota;
    private javax.swing.JLabel lblMontoTotalGasto;
    private javax.swing.JLabel lblNombreGasto;
    private javax.swing.JLabel lblNumCuota;
    private javax.swing.JLabel lblSeparador1;
    private javax.swing.JLabel lblSeparador2;
    private javax.swing.JLabel lblTarjetaAsociada;
    private javax.swing.JLabel lblTipoGasto;
    private javax.swing.JTextField txtAnioGasto;
    private javax.swing.JTextField txtDiaGasto;
    private javax.swing.JTextField txtMesGasto;
    private javax.swing.JTextField txtMontoCuota;
    private javax.swing.JTextField txtMontoTotalGasto;
    private javax.swing.JTextField txtNombreGasto;
    private javax.swing.JTextField txtNumCuotas;
    // End of variables declaration//GEN-END:variables
}
